### ISSUE TITLE
感谢您的视频抠像项目，我没有看到项目视频推理的速度，FPS相关的信息，请问有测试过吗，相比于RVM怎么样呢

### ISSUE THREAD

**Issue by zhanghongyong123456** [nowsyn/SparseMat#2]
![image](https://github.com/nowsyn/SparseMat/assets/48466610/8df82502-30f7-4e31-9b10-889fd8637aaa)

**Comment by nowsyn** [comment]
Our method is based on low-resolution networks and are slower than pure low-resolution matting methods such as RVM, but much faster than patch-based inference. The inference time depends on the image resolution and the sparsity.
