### ISSUE TITLE
Dataset download link

### ISSUE THREAD

**Issue by hmchuong** [nowsyn/SparseMat#3]
Hi,
Thank you for your great work! I do not have the Baidu account to download the data. Could you give us the Google Drive/ One Drive version of the data?

Thanks,

**Comment by nowsyn** [comment]
Currently I cannot provide Google drive or One drive download link because the dataset is very large (nearly 300G) and I have no sufficient free storage quota on the Google/One drive. I am seeking for a platform suitable for everyone.
